### PR TITLE
feat: add vite plugin

### PR DESCRIPTION
**Pull request by ZachJW34**
This plugin is based off of [create-vite-app](https://github.com/vitejs/vite/tree/main/packages/create-app) with the `vue-ts` template
Todo:

- [x] Add documentation
- [x] Configure package.json
- [x] add `nx-plus-vite.png`

### CODE REVIEW

**Comment by ZachJW34** [comment]
Dependent on #193 as I'd like Vite to work with the latest version of Nx and Jest.

**Comment by mrfy** [comment]
up

**Comment by BhaskaranR** [comment]
any update on this PR?

**Comment by ZachJW34** [comment]
I've just released `@nx-plus/vite@12.2.0`. I wanted to publish a beta version but npm didn't listen to me 😓 . Oh well, I tested and it works so try and it out and let me know how it works!

The package currently expects Nx v12 to be installed, I'll be working on updating all our packages to v13 soon. That said, I created an app inside a v12 workspace and migrated to v13 and everything was working so if you want to be on the latest you can try that.

**Pull request merged**
