### PR TITLE
Update to Nx 13.4.3

### PR DESCRIPTION
**Pull request by benpsnyder**
## Related Issue(s)

Fixes #

### CODE REVIEW

**Comment by benpsnyder** [comment]
@ZachJW34 perhaps you can begin the conversion to @nrwl/devkit from this point... please checkout the tip of my branch here and run `nx build docusaurus`

**Comment by ZachJW34** [comment]
Docusaurus has been updated on this branch, we can make it work. It all comes down to making sure everything is stable before I publish new versions, so how we go about it can be either update before or after the nx update. Whatever is easiest, we'll go with
https://github.com/ZachJW34/nx-plus/tree/update-docusaurus-deps

**Comment by ZachJW34** [comment]
Vue is almost updated, I didn't base it on your branch since there are too many changes. I think it will be easier to get them all updated and then incorporate your changes.
https://github.com/ZachJW34/nx-plus/pull/219

**Comment by ZachJW34** [comment]
Pushed all the updated to your branch and updated to latest Nx. Thanks for the contribution @benpsnyder!

**Review by ZachJW34 — APPROVED** [review]

**Pull request merged**
