### PR TITLE
Add static builder for Nuxt

### PR DESCRIPTION
**Pull request by KennyDurand**
Hello,

I needed a way to generate static files for a Nuxt application, so I created a builder for this.

I guessed other people might need it, so here is a PR with this.
I'm open to any comment, I'm still new on NX so I might have missed something.

Cheers!

### CODE REVIEW

**Review by BuckyMaler — CHANGES_REQUESTED** [review]
Thanks for opening this PR! I also think others will find this feature useful.

Update the [app schematic](https://github.com/ZachJW34/nx-plus/blob/master/libs/nuxt/src/schematics/application/schematic.ts#L265) to include a static target so that `nx static <app>` can be ran from the start of an app. For an app named `my-app` the target should look like the following:

```
"static": {
  "executor": "@nx-plus/nuxt:static",
  "options": {
    "browserTarget": "my-app:build:production"
  }
}
```

**Comment by BuckyMaler** [comment]
Thanks for opening this PR! I also think others will find this feature useful.

Let me know if there's anything I can do to help.

**Comment by KennyDurand** [comment]
Hey there,

Sorry for the lack of replies, I had a lot of work recently.
I tried implementing your feedback but I must be missing something on the `scheduleTargetAndForget` because right now the builder completes without running either build or run.

By that time I realised @vancegillies created PR #180 that might already solve the problems. So @BuckyMaler I let you have a look at both our PRs and tell us on which version you prefer to go on.

Let me know how we can work together for this feature!

**Comment by BuckyMaler** [comment]
It's unlikely that I'll be able to review this within the next couple of weeks because of personal obligations. In the meantime, feel free to collaborate with @vancegillies on combining your work in a single PR.

@ZachJW34 I know you're very busy, but if you have time to review this you won't be stepping on my toes.

**Comment by vancegillies** [comment]
@BuckyMaler Sure thing.

@KennyDurand Did you want to merge my changes into this PR? Let me know!

**Comment by ZachJW34** [comment]
Sure I'll review once the PRs are merged or we decide on one over another.

**Comment by KennyDurand** [comment]
@ZachJW34 I think we can close this PR in favor of #180, since @vancegillies has built a more advanced version.

**Pull request closed without merging**
