### PR TITLE
RE Add nuxt static builder

### PR DESCRIPTION
**Pull request by vancegillies**
Hey,

Interested in helping out with this and learning some nx, saw your review @BuckyMaler on #175 and thought I could make the changes. Bit harder than I Initially thought so just making this a draft for some guidance.

I have made you static target have only a browserTarget as an option and updated to builder to use the 'build' target for the actual build.

It still doesn't work, going into the correct folder now but the generate part fails saying it can't find the built files. changed the dir value to '/test' and didn't see any value so I'm lost

also the return value of the builder doesn't feel right but that's what linting would allow.

sorry for the half done PR, ignore if needed

### CODE REVIEW

**Comment by vancegillies** [comment]
Work out the issues and wrote tests, ready for review.

**Comment by BuckyMaler** [comment]
It's unlikely that I'll be able to review this within the next couple of weeks because of personal obligations. In the meantime, feel free to collaborate with @KennyDurand on combining your work in a single PR.

@ZachJW34 I know you're very busy, but if you have time to review this you won't be stepping on my toes.

**Review by ZachJW34 — CHANGES_REQUESTED** [review]
If you feel good about the changes I've suggested, please squash your commits on your next push and then we can get this merged!

**Comment by vancegillies** [comment]
Been very busy past few weeks. Will look at these changes this week at some point hopefully

**Review by ZachJW34 — APPROVED** [review]

**Comment by ZachJW34** [comment]
Thanks for the contribution @vancegillies!

**Pull request merged**
